//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveShot.API.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveShot.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.Canvas.Tooltip.
        /// </summary>
        public static string CaptureScreen_Canvas_Tooltip {
            get {
                return ResourceManager.GetString("CaptureScreen.Canvas.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Arrow.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Arrow {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Close.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Close {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.ColorPicker.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_ColorPicker {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Copy.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Copy {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.EyeDropper.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_EyeDropper {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.EyeDropper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Google.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Google {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Highlighter.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Highlighter {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Highlighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Pencil.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Pencil {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Print.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Print {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Rectangle.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Rectangle {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Save.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Save {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Share.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Share {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///CaptureScreen.CanvasButtons.Stroke.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Stroke {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Text.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Text {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Undo.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Undo {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.CanvasButtons.Upload.
        /// </summary>
        public static string CaptureScreen_CanvasButtons_Upload {
            get {
                return ResourceManager.GetString("CaptureScreen.CanvasButtons.Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.SaveImage.FileName.
        /// </summary>
        public static string CaptureScreen_SaveImage_FileName {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.SaveImage.Title.
        /// </summary>
        public static string CaptureScreen_SaveImage_Title {
            get {
                return ResourceManager.GetString("CaptureScreen.SaveImage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.SizeLabel.Empty.
        /// </summary>
        public static string CaptureScreen_SizeLabel_Empty {
            get {
                return ResourceManager.GetString("CaptureScreen.SizeLabel.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptureScreen.Title.
        /// </summary>
        public static string CaptureScreen_Title {
            get {
                return ResourceManager.GetString("CaptureScreen.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ContextMenu.CaptureScreenShot.Title.
        /// </summary>
        public static string ContextMenu_CaptureScreenShot_Title {
            get {
                return ResourceManager.GetString("ContextMenu.CaptureScreenShot.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ContextMenu.Configuration.Title.
        /// </summary>
        public static string ContextMenu_Configuration_Title {
            get {
                return ResourceManager.GetString("ContextMenu.Configuration.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ContextMenu.Exit.Title.
        /// </summary>
        public static string ContextMenu_Exit_Title {
            get {
                return ResourceManager.GetString("ContextMenu.Exit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception.Message.
        /// </summary>
        public static string Exception_Message {
            get {
                return ResourceManager.GetString("Exception.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExportWindow.Copy.
        /// </summary>
        public static string ExportWindow_Copy {
            get {
                return ResourceManager.GetString("ExportWindow.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExportWindow.Open.
        /// </summary>
        public static string ExportWindow_Open {
            get {
                return ResourceManager.GetString("ExportWindow.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExportWindow.Title.
        /// </summary>
        public static string ExportWindow_Title {
            get {
                return ResourceManager.GetString("ExportWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ExportWindow.Uploading.
        /// </summary>
        public static string ExportWindow_Uploading {
            get {
                return ResourceManager.GetString("ExportWindow.Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imgur.InvalidClientIdException.
        /// </summary>
        public static string Imgur_InvalidClientIdException {
            get {
                return ResourceManager.GetString("Imgur.InvalidClientIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NotifyIcon.Title.
        /// </summary>
        public static string NotifyIcon_Title {
            get {
                return ResourceManager.GetString("NotifyIcon.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.Failed.
        /// </summary>
        public static string Upload_Failed {
            get {
                return ResourceManager.GetString("Upload.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.InvalidUploadType.
        /// </summary>
        public static string Upload_InvalidUpload_Type {
            get {
                return ResourceManager.GetString("Upload.InvalidUpload.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload.Success.
        /// </summary>
        public static string Upload_Success {
            get {
                return ResourceManager.GetString("Upload.Success", resourceCulture);
            }
        }
    }
}
